apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: teams.cmoulliard.com
spec:
  group: cmoulliard.com
  version: v1
  names:
    kind: Team
    listKind: TeamList
    plural: teams
    shortNames:
    - team
    singular: team
  version: v1