# Targeted platform is k8s 1.9 / OpenShift 3.9
[[constraint]]
  name = "k8s.io/client-go"
  version = "6.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.9"

[[constraint]]
  name = "github.com/Sirupsen/logrus"
  version = "1.0.5"